### ISSUE TITLE
all regular pilots in hiring hall are vehicle pilots only, no mech pilots, is this expected

### ISSUE THREAD

**Issue by WizardMarnok** [lordruthermore/BTX_Tanks#1]
After installing this mod and starting a new career, all the character in the hiring hall apart from KS / specials are tank pilots only. There are no mech pilots I have found. 

Is this an install issue I can fix?
Or is it supposed to work this way?

**Comment by lordruthermore** [comment]
The lifenode changes make the low-end pilots more likely to be tank-only. Probably most likely on very poor/minor planets. With better pilots you will have more Mech piloting.
You can also ask on BEX Discord, https://discord.com/channels/558830315083399178/558836927583879170.

**Comment by WizardMarnok** [comment]
Thanks, I'd asked on the discord but I think my question got buried.  I see now I know what to look for, the level1 nodes have the "pilot_vehicle_crew" and "pilot_nomech_crew" added for most of the backgrounds, but they can path out to other levels which have mechwarrior.
